### ISSUE TITLE
Inline Title empty divs render when editTitle is set to false or not specified in "brand"

### ISSUE THREAD

**Issue by cosbyr** [Esri/global-nav#297]
![image](https://user-images.githubusercontent.com/11748268/83302627-8bcceb00-a1b0-11ea-9875-94a4320ee2c1.png)

Not sure if this behavior is by design, but this also leads to ARIA warnings:
![image](https://user-images.githubusercontent.com/11748268/83302785-c5055b00-a1b0-11ea-9527-7c8954e82c60.png)

**Comment by paulcpederson** [comment]
Should be fixed in [📦  v1.4.0](https://github.com/Esri/global-nav/releases/tag/v1.4.0)

**Comment by MikeTschudi** [comment]
@paulcpederson, still appears in 1.4.0

![image](https://user-images.githubusercontent.com/2125181/90448912-30b5e080-e09b-11ea-933a-e6e83ba4040e.png)

**Comment by paulcpederson** [comment]
@MikeTschudi are you getting a11y errors for this? AFAIK `display: none` applied to the entire `esri-header-inline-title`  should prevent readers from announcing this content?

**Comment by MikeTschudi** [comment]
@paulcpederson, yes:  WAVE reports 
an "empty button":
```html
<button class="esri-header-inline-title-control" id="esri-header-inline-title-control" tabindex="-1" aria-expanded="false" aria-controls="esri-header-inline-title-content"></button>
```

and two "broken ARIA references" (`#esri-header-inline-title-action-button` is missing for both):
```html
<button class="esri-header-inline-title-action-button esri-header-inline-title-dismiss-button" aria-labelledby="esri-header-inline-title-action-button" style="outline: red dashed 2px;"></button>
```
```html
<button class="esri-header-inline-title-action-button esri-header-inline-title-submit-button" aria-labelledby="esri-header-inline-title-action-button"></button>
```

I see that global-nav applied the class "hidden" to the `#esri-header-inline-title`.

**Comment by paulcpederson** [comment]
@MikeTschudi OK, this is going to be quite a lot of work. The dev that built the global nav built it on an event architecture that revolves around custom events. I will take a look around and see if I can figure out a work around...

**Comment by MikeTschudi** [comment]
@paulcpederson, thanks. This is not a priority for our project because we run a workaround
```
this.removeElement(document.getElementById("esri-header-inline-title"));
```
